name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
          target: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
      - run: npm ci
      - run: npm run lint
      - run: npm run package
      - run: npm run test

  rust-tests-clippy-warnings:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --all-features
          working-directory: rust_tests/clippy_warnings
      - run: |
          echo 'rustc version: $CI_RUSTC_VERSION'
          echo 'cargo version: $CI_CARGO_VERSION'
          echo 'tool version: $CI_TOOL_VERSION'
          echo 'clippy version: $CI_CLIPPY_VERSION'
          
          echo 'Internal Compiler Errors: $CI_INTERNAL_COMPILER_ERRORS'
          echo 'Errors: $CI_ERRORS'
          echo 'Warnings: $CI_WARNINGS'
          echo 'Notes: $CI_NOTES'
          echo 'Help: $CI_HELP'
        env:
          CI_RUSTC_VERSION: ${{ steps.clippy-check.outputs.rustc-version }}
          CI_CARGO_VERSION: ${{ steps.clippy-check.outputs.cargo-version }}
          CI_TOOL_VERSION: ${{ steps.clippy-check.outputs.tool-version}}
          CI_CLIPPY_VERSION: ${{ steps.clippy-check.outputs.clippy-version }}

          CI_INTERNAL_COMPILER_ERRORS: ${{ steps.clippy-check.outputs.internal-compiler-errors }}
          CI_ERRORS: ${{ steps.clippy-check.outputs.errors }}
          CI_WARNINGS: ${{ steps.clippy-check.outputs.warnings }}
          CI_NOTES: ${{ steps.clippy-check.outputs.notes }}
          CI_HELP: ${{ steps.clippy-check.outputs.help }}

  rust-tests-cross:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          target: aarch64-unknown-linux-gnu
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --target aarch64-unknown-linux-gnu --all-features
          working-directory: rust_tests/clippy_warnings
          tool: cross
          cache-key: 'rs-clippy-check-tests'
      - run: |
          echo 'rustc version: $CI_RUSTC_VERSION'
          echo 'cargo version: $CI_CARGO_VERSION'
          echo 'tool version: $CI_TOOL_VERSION'
          echo 'clippy version: $CI_CLIPPY_VERSION'

          echo 'Internal Compiler Errors: $CI_INTERNAL_COMPILER_ERRORS'
          echo 'Errors: $CI_ERRORS'
          echo 'Warnings: $CI_WARNINGS'
          echo 'Notes: $CI_NOTES'
          echo 'Help: $CI_HELP'
        env:
          CI_RUSTC_VERSION: ${{ steps.clippy-check.outputs.rustc-version }}
          CI_CARGO_VERSION: ${{ steps.clippy-check.outputs.cargo-version }}
          CI_TOOL_VERSION: ${{ steps.clippy-check.outputs.tool-version}}
          CI_CLIPPY_VERSION: ${{ steps.clippy-check.outputs.clippy-version }}

          CI_INTERNAL_COMPILER_ERRORS: ${{ steps.clippy-check.outputs.internal-compiler-errors }}
          CI_ERRORS: ${{ steps.clippy-check.outputs.errors }}
          CI_WARNINGS: ${{ steps.clippy-check.outputs.warnings }}
          CI_NOTES: ${{ steps.clippy-check.outputs.notes }}
          CI_HELP: ${{ steps.clippy-check.outputs.help }}

  rust-tests-cargo-hack:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --feature-powerset
          working-directory: rust_tests/clippy_warnings
          tool: cargo-hack
          cache-key: 'rs-clippy-check-tests'
      - run: |
          echo 'rustc version: $CI_RUSTC_VERSION'
          echo 'cargo version: $CI_CARGO_VERSION'
          echo 'tool version: $CI_TOOL_VERSION'
          echo 'clippy version: $CI_CLIPPY_VERSION'

          echo 'Internal Compiler Errors: $CI_INTERNAL_COMPILER_ERRORS'
          echo 'Errors: $CI_ERRORS'
          echo 'Warnings: $CI_WARNINGS'
          echo 'Notes: $CI_NOTES'
          echo 'Help: $CI_HELP'
        env:
          CI_RUSTC_VERSION: ${{ steps.clippy-check.outputs.rustc-version }}
          CI_CARGO_VERSION: ${{ steps.clippy-check.outputs.cargo-version }}
          CI_TOOL_VERSION: ${{ steps.clippy-check.outputs.tool-version}}
          CI_CLIPPY_VERSION: ${{ steps.clippy-check.outputs.clippy-version }}

          CI_INTERNAL_COMPILER_ERRORS: ${{ steps.clippy-check.outputs.internal-compiler-errors }}
          CI_ERRORS: ${{ steps.clippy-check.outputs.errors }}
          CI_WARNINGS: ${{ steps.clippy-check.outputs.warnings }}
          CI_NOTES: ${{ steps.clippy-check.outputs.notes }}
          CI_HELP: ${{ steps.clippy-check.outputs.help }}
