name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: clippy
          matcher: false
          rustflags: ""
          target: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
      - run: npm ci
      - run: npm run lint
      - run: npm run package
      - run: npm run test

  rust-tests-clippy-warnings:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --all-features
          working-directory: rust_tests/clippy_warnings
      - name: Check action outputs
        run: |
          echo "rustc version: ${{ steps.clippy-check.outputs.rustc-version }}"
          echo "cargo version: ${{ steps.clippy-check.outputs.cargo-version }}"
          echo "tool version: ${{ steps.clippy-check.outputs.tool-version }}"
          echo "clippy version: ${{ steps.clippy-check.outputs.clippy-version }}"

          echo "Internal Compiler Errors: ${{ steps.clippy-check.outputs.internal-compiler-errors }}"
          echo "Errors: ${{ steps.clippy-check.outputs.errors }}"
          echo "Warnings: ${{ steps.clippy-check.outputs.warnings }}"
          echo "Notes: ${{ steps.clippy-check.outputs.notes }}"
          echo "Help: ${{ steps.clippy-check.outputs.help }}"

  rust-tests-cross:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          target: aarch64-unknown-linux-gnu
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --target aarch64-unknown-linux-gnu --all-features
          working-directory: rust_tests/clippy_warnings
          tool: cross
          cache-key: 'rs-clippy-check-tests'
      - name: Check action outputs
        run: |
          echo "rustc version: ${{ steps.clippy-check.outputs.rustc-version }}"
          echo "cargo version: ${{ steps.clippy-check.outputs.cargo-version }}"
          echo "tool version: ${{ steps.clippy-check.outputs.tool-version }}"
          echo "clippy version: ${{ steps.clippy-check.outputs.clippy-version }}"

          echo "Internal Compiler Errors: ${{ steps.clippy-check.outputs.internal-compiler-errors }}"
          echo "Errors: ${{ steps.clippy-check.outputs.errors }}"
          echo "Warnings: ${{ steps.clippy-check.outputs.warnings }}"
          echo "Notes: ${{ steps.clippy-check.outputs.notes }}"
          echo "Help: ${{ steps.clippy-check.outputs.help }}"

  rust-tests-cargo-hack:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --feature-powerset
          working-directory: rust_tests/clippy_warnings
          tool: cargo-hack
          cache-key: 'rs-clippy-check-tests'
      - name: Check action outputs
        run: |
          echo "rustc version: ${{ steps.clippy-check.outputs.rustc-version }}"
          echo "cargo version: ${{ steps.clippy-check.outputs.cargo-version }}"
          echo "tool version: ${{ steps.clippy-check.outputs.tool-version }}"
          echo "clippy version: ${{ steps.clippy-check.outputs.clippy-version }}"

          echo "Internal Compiler Errors: ${{ steps.clippy-check.outputs.internal-compiler-errors }}"
          echo "Errors: ${{ steps.clippy-check.outputs.errors }}"
          echo "Warnings: ${{ steps.clippy-check.outputs.warnings }}"
          echo "Notes: ${{ steps.clippy-check.outputs.notes }}"
          echo "Help: ${{ steps.clippy-check.outputs.help }}"
