name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
          target: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
      - run: npm ci
      - run: npm run lint
      - run: npm run package
      - run: npm run test

  rust-tests-clippy-warnings:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --all-features
          working-directory: rust_tests/clippy_warnings

  rust-tests-cross:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          target: aarch64-unknown-linux-gnu
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --target aarch64-unknown-linux-gnu --all-features
          working-directory: rust_tests/clippy_warnings
          tool: cross
          cache-key: 'rs-clippy-check-tests'

  rust-tests-cargo-hack:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          components: clippy
          matcher: false
          rustflags: ""
      - uses: ./
        id: clippy-check
        with:
          args: --feature-powerset
          working-directory: rust_tests/clippy_warnings
          tool: cargo-hack
          cache-key: 'rs-clippy-check-tests'
      - name: Check action outputs
        run: |
          echo "rustc version: ${{ steps.clippy-check.outputs.rustc-version }}"
          echo "cargo version: ${{ steps.clippy-check.outputs.cargo-version }}"
          echo "tool version: ${{ steps.clippy-check.outputs.tool-version }}"
          echo "clippy version: ${{ steps.clippy-check.outputs.clippy-version }}"

          echo "Internal Compiler Errors: ${{ steps.clippy-check.outputs.internal-compiler-errors }}"
          echo "Errors: ${{ steps.clippy-check.outputs.errors }}"
          echo "Warnings: ${{ steps.clippy-check.outputs.warnings }}"
          echo "Notes: ${{ steps.clippy-check.outputs.notes }}"
          echo "Help: ${{ steps.clippy-check.outputs.help }}"
